import test from 'node:test'
import assert from 'node:assert/strict'
import { buildCapacityAlertConditions, evaluateCapacityAlerts, transitionCapacityAlert } from '../src/ops/capacity/alerts.js'
const hostProfileId='host-1'; const condition={type:'disk_usage',breached:true,severity:'attention',observedValues:{diskUsedPercent:80,token:'omit-me'},recommendation:'Revisar disco'}
test('lifecycle exige duas amostras, aplica cooldown e recuperação dupla',()=>{ const t0=new Date('2026-08-27T00:00:00Z'); const a=transitionCapacityAlert(null,condition,{hostProfileId,now:t0}); assert.equal(a.status,'pending'); const b=transitionCapacityAlert(a,condition,{hostProfileId,now:new Date(t0.getTime()+300000)}); assert.equal(b.status,'active'); assert.equal(b.notify,true); const c=transitionCapacityAlert(b,condition,{hostProfileId,now:new Date(t0.getTime()+600000)}); assert.equal(c.notify,false); const d=transitionCapacityAlert(c,{...condition,breached:false},{hostProfileId,now:new Date(t0.getTime()+900000)}); assert.equal(d.status,'active'); const e=transitionCapacityAlert(d,{...condition,breached:false},{hostProfileId,now:new Date(t0.getTime()+1200000)}); assert.equal(e.status,'recovered'); assert.equal(e.recoveryNotify,true) })
test('piora ignora cooldown e chave deduplica host/tipo',()=>{ const old={status:'active',severity:'attention',consecutiveBreaches:2,consecutiveRecoveries:0,firstObservedAt:new Date(),lastNotifiedAt:new Date()}; const next=transitionCapacityAlert(old,{...condition,severity:'critical'},{hostProfileId,now:new Date()}); assert.equal(next.notify,true); assert.equal(next.conditionKey,'host-1:disk_usage') })

test('avalia todas as condições operacionais com evidência mínima',()=>{ const now=new Date('2026-08-27T14:30:00Z'); const conditions=buildCapacityAlertConditions({collectedAt:'2026-08-27T12:00:00Z',operationalState:'plan_now',headroomSessions:1,forecastHorizonDays:10,memoryTotalMb:8192,memoryAvailableMb:1000,swapOutKbPerSec:12,diskUsedPercent:86,oomKillCount:2,productionWorkers:17,connectedSessions:16,stagingOnline:true,stagingWorkers:0,stagingRssMb:315,stagingIdleMinutes:1440},{now,previous:{oomKillCount:1}}); assert.deepEqual(conditions.map(c=>c.type),['capacity_margin','forecast_horizon','swap_pressure','disk_usage','oom_kill','collection_stale','worker_session_divergence','staging_idle']); assert.ok(conditions.every(c=>c.breached)); assert.doesNotMatch(JSON.stringify(conditions),/token|secret|cookie/i) })

test('staging só alerta após 24 horas ocioso',()=>{ const before=buildCapacityAlertConditions({stagingOnline:true,stagingWorkers:0,stagingIdleMinutes:1439}); const after=buildCapacityAlertConditions({stagingOnline:true,stagingWorkers:0,stagingIdleMinutes:1440}); assert.equal(before.find(c=>c.type==='staging_idle').breached,false); assert.equal(after.find(c=>c.type==='staging_idle').breached,true) })

test('idade da coleta avança pelo relógio mesmo reutilizando o último snapshot',()=>{ const stale=buildCapacityAlertConditions({collectedAt:'2026-08-27T12:00:00Z'},{now:new Date('2026-08-27T14:01:00Z'),previous:{collectedAt:'2026-08-27T12:00:00Z'}}).find(c=>c.type==='collection_stale'); assert.equal(stale.breached,true); assert.equal(stale.observedValues.ageMinutes,121) })

test('OOM único fica latched para confirmação e reincidência reinicia firstObservedAt',async()=>{ const records=new Map(); const notifications=[]; const repository={listAlerts:async()=>[...records.values()],upsertAlert:async(a)=>(records.set(a.type,{...a,observedValues:a.observedValues}),a),createEvent:async()=>{}}; const host={id:'h'}; const base={collectedAt:'2026-08-27T00:05:00Z',policyVersion:'v1',oomKillCount:1}; await evaluateCapacityAlerts({repository,host,snapshot:base,previous:{oomKillCount:0},now:new Date('2026-08-27T00:05:00Z'),notify:a=>notifications.push(a)}); await evaluateCapacityAlerts({repository,host,snapshot:{...base,collectedAt:'2026-08-27T00:10:00Z'},previous:base,now:new Date('2026-08-27T00:10:00Z'),notify:a=>notifications.push(a)}); assert.equal(records.get('oom_kill').status,'active'); assert.equal(notifications.filter(a=>a.type==='oom_kill').length,1); await evaluateCapacityAlerts({repository,host,snapshot:{...base,collectedAt:'2026-08-27T00:15:00Z'},previous:base,now:new Date('2026-08-27T00:15:00Z')}); await evaluateCapacityAlerts({repository,host,snapshot:{...base,collectedAt:'2026-08-27T00:20:00Z'},previous:base,now:new Date('2026-08-27T00:20:00Z')}); assert.equal(records.get('oom_kill').status,'recovered'); const recurrenceAt=new Date('2026-08-28T01:00:00Z'); await evaluateCapacityAlerts({repository,host,snapshot:{...base,oomKillCount:2,collectedAt:recurrenceAt},previous:base,now:recurrenceAt}); assert.equal(new Date(records.get('oom_kill').firstObservedAt).getTime(),recurrenceAt.getTime()) })
