import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import { createSalesState, errorGuidance, salesReducer, STABLE_ERROR_CODES, validateCustomPeriod } from '../dashboard/app/painel/vendas/salesLifecycle.js'
const reduce=(state,...actions)=>actions.reduce(salesReducer,state)
const period={from:'2026-08-21',to:'2026-08-27'}
test('Vendas vem imediatamente após Painel',()=>{const n=fs.readFileSync(new URL('../dashboard/app/painel/nav.js',import.meta.url),'utf8');assert.ok(n.indexOf("label: 'Painel'")<n.indexOf("label: 'Vendas'"));assert.ok(n.indexOf("label: 'Vendas'")<n.indexOf("title: 'Criar & enviar'"))})
test('lifecycle executável: carregamento inicial, sucesso e vazio',()=>{let state=createSalesState(period);assert.equal(state.loading,true);state=reduce(state,{type:'request-start',request:1},{type:'request-success',request:1,snapshot:{summary:{attributedPurchases:2},sourceUpdatedAt:'2026-08-27T10:00:00Z'}});assert.equal(state.loading,false);assert.equal(state.snapshot.summary.attributedPurchases,2);state=reduce(state,{type:'request-start',request:2},{type:'request-success',request:2,snapshot:{summary:{attributedPurchases:0},sourceUpdatedAt:'2026-08-27T11:00:00Z'}});assert.equal(state.snapshot.summary.attributedPurchases,0)})
test('todos os erros estáveis têm orientação e retry executável',()=>{for(const code of STABLE_ERROR_CODES){let state=reduce(createSalesState(period),{type:'request-start',request:1},{type:'request-error',request:1,error:{code,retryable:code.includes('UNAVAILABLE')}});assert.equal(state.error.code,code);assert.ok(errorGuidance(code).length>20);state=salesReducer(state,{type:'retry'});assert.equal(state.retry,1)}})
test('falha preserva snapshot e timestamp anterior até sucesso posterior',()=>{const old={summary:{attributedPurchases:1},sourceUpdatedAt:'2026-08-27T10:00:00Z'};let state=reduce(createSalesState(period),{type:'request-start',request:1},{type:'request-success',request:1,snapshot:old},{type:'request-start',request:2},{type:'request-error',request:2,error:{code:'SHOPEE_UNAVAILABLE',retryable:true}});assert.equal(state.snapshot,old);assert.equal(state.snapshot.sourceUpdatedAt,old.sourceUpdatedAt);const fresh={summary:{attributedPurchases:3},sourceUpdatedAt:'2026-08-27T11:00:00Z'};state=reduce(state,{type:'request-start',request:3},{type:'request-success',request:3,snapshot:fresh});assert.equal(state.snapshot,fresh)})
test('abort e respostas fora de ordem são ignorados',()=>{const initial=createSalesState(period);let state=reduce(initial,{type:'request-start',request:1},{type:'request-start',request:2});const same=salesReducer(state,{type:'request-success',request:1,snapshot:{secret:'old'}});assert.equal(same,state);state=salesReducer(state,{type:'request-error',request:2,aborted:true,error:{code:'SHOPEE_UNAVAILABLE'}});assert.equal(state.error,null);assert.equal(state.loading,true);state=salesReducer(state,{type:'request-finish',request:2});assert.equal(state.loading,false)})
test('validação customizada rejeita datas impossíveis, futuras e limites',()=>{assert.equal(validateCustomPeriod(period,'2026-08-27'),true);assert.equal(validateCustomPeriod({from:'2026-02-30',to:'2026-03-01'},'2026-08-27'),false);assert.equal(validateCustomPeriod({from:'2026-08-27',to:'2026-08-28'},'2026-08-27'),false);assert.equal(validateCustomPeriod({from:'2026-01-01',to:'2026-08-01'},'2026-08-27'),false)})
test('preset reseta páginas; paginações são independentes e preservam filtro',()=>{let state=createSalesState(period);state=reduce(state,{type:'page',name:'orderPage',value:3},{type:'page',name:'productPage',value:4});assert.deepEqual(state.pages,{orderPage:3,productPage:4});assert.equal(state.period,period);state=salesReducer(state,{type:'page',name:'orderPage',value:2});assert.deepEqual(state.pages,{orderPage:2,productPage:4});const next={from:'2026-08-27',to:'2026-08-27'};state=salesReducer(state,{type:'period',period:next});assert.equal(state.period,next);assert.deepEqual(state.pages,{orderPage:1,productPage:1})})
test('draft não altera período até aplicação e erro de validação é estável',()=>{let state=createSalesState(period);state=salesReducer(state,{type:'draft',field:'from',value:'2026-02-30'});assert.equal(state.period,period);state=salesReducer(state,{type:'validation-error',message:'corrija'});assert.deepEqual(state.error,{code:'INVALID_PERIOD',message:'corrija',retryable:false})})
