import test from 'node:test'
import assert from 'node:assert/strict'
import { buildSalesSnapshot, classifyStatus, createShopeeSalesService, validateSalesQuery } from '../src/shopeeSales/service.js'
import { conversionReportQuery, splitSourceWindows } from '../src/shopeeSales/report.js'
import { createShopeeSalesClient } from '../src/shopeeSales/client.js'
import crypto from 'node:crypto'
test('query-only e janelas limitadas',()=>{assert.match(conversionReportQuery({start:1,end:2}),/^query/);assert.doesNotMatch(conversionReportQuery({start:1,end:2}),/mutation/i);assert.equal(splitSourceWindows(0,30*86400000).length,5)})
test('valida período',()=>{assert.equal(validateSalesQuery({from:'2026-08-01',to:'2026-08-27'}).limit,20);assert.throws(()=>validateSalesQuery({from:'2026-07-01',to:'2026-08-27'}),/30 dias/)})
test('rejeita data impossível e intervalo futuro',()=>{assert.throws(()=>validateSalesQuery({from:'2026-02-30',to:'2026-03-01'}),/calendário/);assert.throws(()=>validateSalesQuery({from:'2099-01-01',to:'2099-01-02'}),/futuro/)})
test('atribuição por prefixo, dedupe e finanças canônicas',()=>{const q=validateSalesQuery({from:'2026-08-01',to:'2026-08-01'});const c={conversionId:'c1',utmContent:'espelhagrupos----',purchaseTime:1785542400,conversionStatus:'CONFIRMED',estimatedTotalCommission:2,netCommission:1.5,orders:[{orderId:'o1',orderStatus:'CONFIRMED',items:[{itemId:'i1',qty:2,actualAmount:10,itemName:'Oferta'}]}]};const out=buildSalesSnapshot([c,c,{...c,conversionId:'c2',utmContent:'outro'}],q);assert.equal(out.summary.attributedPurchases,1);assert.equal(out.summary.salesAmount,10);assert.equal(out.summary.estimatedCommission,2);assert.equal(out.summary.confirmedCommission,1.5);assert.equal(out.summary.itemQuantity,2);assert.equal(JSON.stringify(out).includes('conversionId'),false)})
test('status desconhecido não é confirmado',()=>assert.equal(classifyStatus('novo'),'unclassified'))
test('cliente assina payload e percorre todos os scrollIds',async()=>{const calls=[];const http={post:async(url,body,config)=>{calls.push({url,body,config});return {data:{data:{conversionReport:calls.length===1?{nodes:[{conversionId:'1'}],pageInfo:{hasNextPage:true,scrollId:'next'}}:{nodes:[{conversionId:'2'}],pageInfo:{hasNextPage:false,scrollId:''}}}}}}};const rows=await createShopeeSalesClient({http}).readWindow({appId:'app',secretKey:'secret'},{start:1,end:2});assert.equal(rows.length,2);assert.match(calls[1].body.query,/scrollId: "next"/);assert.match(calls[0].body.query,/purchaseTimeStart: 1, purchaseTimeEnd: 2/);const auth=calls[0].config.headers.Authorization;const [,timestamp,signature]=auth.match(/Timestamp=(\d+), Signature=([a-f0-9]+)/);assert.equal(signature,crypto.createHash('sha256').update(`app${timestamp}${JSON.stringify(calls[0].body)}secret`).digest('hex'))})
test('cliente rejeita cursor ausente/repetido, limite de páginas, registros e nodes malformados',async()=>{const credentials={appId:'a',secretKey:'s'};for(const pageInfo of [{hasNextPage:true,scrollId:''},{hasNextPage:true,scrollId:'same'}]){let n=0;const http={post:async()=>({data:{data:{conversionReport:{nodes:[],pageInfo:n++?pageInfo:{hasNextPage:true,scrollId:'same'}}}}})};await assert.rejects(createShopeeSalesClient({http}).readWindow(credentials,{start:1,end:2}),e=>e.code==='SHOPEE_REPORT_INCOMPLETE')}const endless={post:async()=>({data:{data:{conversionReport:{nodes:[],pageInfo:{hasNextPage:true,scrollId:Math.random().toString()}}}}})};await assert.rejects(createShopeeSalesClient({http:endless,maxPages:1}).readWindow(credentials,{start:1,end:2}),e=>e.code==='SHOPEE_REPORT_INCOMPLETE');const tooMany={post:async()=>({data:{data:{conversionReport:{nodes:[{},{}],pageInfo:{hasNextPage:false}}}}})};await assert.rejects(createShopeeSalesClient({http:tooMany,maxRecords:1}).readWindow(credentials,{start:1,end:2}));const malformed={post:async()=>({data:{data:{conversionReport:{nodes:{},pageInfo:{hasNextPage:false}}}}})};await assert.rejects(createShopeeSalesClient({http:malformed}).readWindow(credentials,{start:1,end:2}))})
test('timeout, autenticação e falha posterior descartam snapshot parcial',async()=>{for(const [error,code,retryable] of [[Object.assign(new Error('timeout'),{code:'ECONNABORTED'}),'SHOPEE_UNAVAILABLE',true],[{response:{status:403}},'SHOPEE_CREDENTIAL_REJECTED',false]]){const http={post:async()=>{throw error}};await assert.rejects(createShopeeSalesClient({http}).readWindow({appId:'a',secretKey:'s'},{start:1,end:2}),e=>e.code===code&&e.retryable===retryable)}let n=0;const http={post:async()=>{if(n++)throw new Error('later');return {data:{data:{conversionReport:{nodes:[{conversionId:'partial'}],pageInfo:{hasNextPage:true,scrollId:'2'}}}}}}};await assert.rejects(createShopeeSalesClient({http}).readWindow({appId:'a',secretKey:'s'},{start:1,end:2}),e=>e.code==='SHOPEE_UNAVAILABLE')})
test('dedupe sem conversionId é estável e finanças incompletas ficam indisponíveis',()=>{const q=validateSalesQuery({from:'2026-08-01',to:'2026-08-01'});const base={checkoutId:'checkout',utmContent:'espelhagrupos----',purchaseTime:1785542400,conversionStatus:'CONFIRMED',estimatedTotalCommission:null,netCommission:null,orders:[{orderId:'o',orderStatus:'CONFIRMED',items:[{itemId:'i',modelId:'m',qty:2,actualAmount:null},{itemId:'i',modelId:'m',qty:2,actualAmount:null}]}]};const out=buildSalesSnapshot([base,{...base}],q);assert.equal(out.summary.attributedPurchases,1);assert.equal(out.summary.salesAmount,null);assert.equal(out.summary.estimatedCommission,null);assert.equal(out.summary.confirmedCommission,null);assert.equal(out.summary.itemQuantity,2);assert.equal(out.products.total,1)})
test('multi-pedido não replica comissão de conversão',()=>{const q=validateSalesQuery({from:'2026-08-01',to:'2026-08-01'});const out=buildSalesSnapshot([{conversionId:'c',utmContent:'espelhagrupos',purchaseTime:1785542400,conversionStatus:'CONFIRMED',estimatedTotalCommission:9,netCommission:8,orders:[{orderId:'a',items:[]},{orderId:'b',items:[]}]}],q);assert.equal(out.summary.estimatedCommission,9);assert.deepEqual(out.orders.rows.map(r=>r.estimatedCommission),[null,null]);assert.ok(out.orders.rows.every(r=>r.commissionScope==='multiple_orders'))})
test('itens repetidos são deduplicados, modelos distintos permanecem',()=>{const q=validateSalesQuery({from:'2026-08-01',to:'2026-08-01'});const item={itemId:'i',modelId:'a',qty:2,actualAmount:10};const out=buildSalesSnapshot([{conversionId:'c',utmContent:'espelhagrupos',estimatedTotalCommission:1,orders:[{orderId:'o',items:[item,{...item},{...item,modelId:'b',qty:1,actualAmount:3}]}]}],q);assert.equal(out.products.total,2);assert.equal(out.summary.itemQuantity,3);assert.equal(out.summary.salesAmount,13)})
test('serviço isola credencial e conversões por tenant',async()=>{const stored={alice:{appId:'app-a',secretKey:'secret-a'},bob:{appId:'app-b',secretKey:'secret-b'}};const lookups=[];const database={credential:{findFirst:async options=>{lookups.push(options);const credential=stored[options.where.userId];return credential?{data:JSON.stringify(credential)}:null}}};const upstream=[];const client={readWindow:async credentials=>{upstream.push(credentials);return credentials.appId==='app-a'?[{conversionId:'alice-sale',utmContent:'espelhagrupos',estimatedTotalCommission:1,orders:[]}]:[{conversionId:'bob-sale',utmContent:'espelhagrupos',estimatedTotalCommission:99,orders:[]}]}};const service=createShopeeSalesService({database,client});const result=await service.getSnapshot('alice',{from:'2026-08-01',to:'2026-08-01'});assert.deepEqual(lookups,[{where:{userId:'alice',platform:'shopee'},select:{data:true}}]);assert.ok(upstream.length>0);assert.ok(upstream.every(value=>value.appId==='app-a'&&value.secretKey==='secret-a'));assert.equal(result.summary.attributedPurchases,1);assert.equal(result.summary.estimatedCommission,1);assert.doesNotMatch(JSON.stringify(result),/bob|99|app-b|secret-b/)})
test('detalhe estrutural ausente não fabrica venda zero',()=>{const q=validateSalesQuery({from:'2026-08-01',to:'2026-08-01'});const base={utmContent:'espelhagrupos',estimatedTotalCommission:0};for(const [name,conversion] of [['sem pedidos',{...base,conversionId:'a'}],['pedidos vazios',{...base,conversionId:'b',orders:[]}],['sem items',{...base,conversionId:'c',orders:[{orderId:'o'}]}],['items vazios',{...base,conversionId:'d',orders:[{orderId:'o',items:[]}]}]]){const out=buildSalesSnapshot([conversion],q);assert.equal(out.summary.salesAmount,null,name);if(out.orders.rows[0])assert.equal(out.orders.rows[0].amount,null,name)}})
test('zero reportado é preservado como zero, não indisponível',()=>{const q=validateSalesQuery({from:'2026-08-01',to:'2026-08-01'});const out=buildSalesSnapshot([{conversionId:'z',utmContent:'espelhagrupos',estimatedTotalCommission:0,orders:[{orderId:'o',items:[{itemId:'i',modelId:'m',qty:0,actualAmount:0,itemTotalCommission:0}]}]}],q);assert.equal(out.summary.salesAmount,0);assert.equal(out.orders.rows[0].amount,0);assert.equal(out.products.rows[0].amount,0);assert.equal(out.summary.estimatedCommission,0)})
