import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import Fastify from 'fastify'
import { shopeeSalesRoutes } from '../src/api/routes/shopeeSales.js'
async function make(service,auth=true){const app=Fastify();app.decorate('authenticate',async(req,reply)=>{if(!auth)return reply.code(401).send({error:'Não autorizado'});req.user={sub:'owner'}});await app.register(shopeeSalesRoutes,{service});return app}
test('usa exclusivamente usuário autenticado',async()=>{let seen;const app=await make({getSnapshot:async id=>(seen=id,{ok:true})});const res=await app.inject({url:'/?from=2026-08-01&to=2026-08-01'});assert.equal(res.statusCode,200);assert.equal(seen,'owner');await app.close()})
test('exige autenticação',async()=>{const app=await make({getSnapshot:async()=>({})},false);assert.equal((await app.inject({url:'/'})).statusCode,401);await app.close()})
test('mapeia erros seguros',async()=>{const app=await make({getSnapshot:async()=>{throw Object.assign(new Error('Configure sua credencial.'),{code:'SHOPEE_NOT_CONFIGURED'})}});const res=await app.inject({url:'/'});assert.equal(res.statusCode,404);assert.deepEqual(res.json(),{error:'Configure sua credencial da Shopee para ver as vendas.',code:'SHOPEE_NOT_CONFIGURED',retryable:false});await app.close()})
test('não vaza detalhes de erros desconhecidos',async()=>{const app=await make({getSnapshot:async()=>{throw new Error('secretKey=segredo banco interno')}});const res=await app.inject({url:'/'});assert.equal(res.statusCode,502);assert.deepEqual(res.json(),{error:'Não foi possível consultar a Shopee.',code:'SHOPEE_UNAVAILABLE',retryable:true});assert.doesNotMatch(res.body,/segredo|secretKey/);await app.close()})
test('encaminha todos os filtros sem aceitar identidade do cliente na query',async()=>{let id,query;const app=await make({getSnapshot:async(a,b)=>(id=a,query=b,{ok:true})});await app.inject({url:'/?from=2026-08-01&to=2026-08-02&orderPage=2&productPage=3&limit=10&timeZone=America%2FSao_Paulo&userId=intruso'});assert.equal(id,'owner');assert.equal(query.orderPage,'2');assert.equal(query.productPage,'3');assert.equal(query.limit,'10');await app.close()})
test('mapeia todos os códigos documentados sem vazar detalhes',async()=>{for(const [code,status,retryable] of [['INVALID_PERIOD',400,false],['SHOPEE_NOT_CONFIGURED',404,false],['SHOPEE_CREDENTIAL_REJECTED',422,false],['SHOPEE_UNAVAILABLE',502,true],['SHOPEE_REPORT_INCOMPLETE',502,true]]){const app=await make({getSnapshot:async()=>{throw Object.assign(new Error('Mensagem segura'),{code,retryable})}});const res=await app.inject({url:'/'});assert.equal(res.statusCode,status);assert.equal(res.json().code,code);assert.equal(res.json().retryable,retryable);assert.doesNotMatch(res.json().error,/Mensagem segura/);await app.close()}})
test('allowlist recursiva remove segredo e PII em todos os níveis',async()=>{const fixture={userId:'owner',secretKey:'root',period:{from:'2026-08-01',to:'2026-08-01',timeZone:'America/Sao_Paulo',buyerEmail:'x'},summary:{attributedPurchases:1,orderCount:1,itemQuantity:1,salesAmount:10,estimatedCommission:2,confirmedCommission:null,internal:'x',statusCounts:{pending:1,unpaid:0,confirmed:0,cancelled:0,refunded:0,unclassified:0,buyer:4}},orders:{page:1,limit:20,total:1,hasNextPage:false,secret:'x',rows:[{id:'opaque',purchasedAt:null,convertedClickAt:null,status:'pending',rawStatusLabel:'PENDING',amount:10,estimatedCommission:2,confirmedCommission:null,commissionScope:'conversion',itemCount:1,orderId:'raw',buyerPhone:'x'}]},products:{page:1,limit:20,total:1,hasNextPage:false,internal:'x',rows:[{id:'opaque2',name:'Produto',shopName:'Loja',quantity:1,amount:10,status:'pending',estimatedCommission:2,imageUrl:null,purchasedAt:null,itemId:'raw',appId:'x'}]},sourceUpdatedAt:'2026-08-01T00:00:00.000Z',stale:false,clickCoverage:'converted_clicks_only',rawPayload:{conversionId:'x'}};const app=await make({getSnapshot:async()=>fixture});const res=await app.inject({url:'/'});assert.equal(res.statusCode,200);assert.equal(res.json().orders.rows[0].id,'opaque');assert.equal(res.json().products.rows[0].name,'Produto');assert.doesNotMatch(res.body,/userId|appId|secretKey|conversionId|checkoutId|orderId|itemId|buyer|internal|rawPayload|secret/i);await app.close()})
test('mensagens públicas fixas removem segredo até de erros conhecidos',async()=>{for(const code of ['INVALID_PERIOD','SHOPEE_NOT_CONFIGURED','SHOPEE_CREDENTIAL_REJECTED','SHOPEE_UNAVAILABLE','SHOPEE_REPORT_INCOMPLETE']){const app=await make({getSnapshot:async()=>{throw Object.assign(new Error('CPF 123 secretKey=roubada'),{code,retryable:true})}});const res=await app.inject({url:'/'});assert.equal(res.json().code,code);assert.doesNotMatch(res.body,/CPF|123|secretKey|roubada/);await app.close()}})
test('OpenAPI fecha recursivamente todos os objetos públicos',()=>{const yaml=fs.readFileSync(new URL('../specs/014-shopee-sales-dashboard/contracts/shopee-sales.openapi.yaml',import.meta.url),'utf8');for(const schema of ['OrderPage','ProductPage','OrderRow','ProductRow','StatusCounts','SalesSnapshot','Error']){const block=yaml.split(`    ${schema}:`)[1]?.split(/^    \w/m)[0]||'';assert.match(block,/additionalProperties: false/,schema)}const snapshot=yaml.split('    SalesSnapshot:')[1].split('    Error:')[0];assert.match(snapshot,/period:\n\s+type: object\n\s+additionalProperties: false/);assert.match(snapshot,/summary:\n\s+type: object\n\s+additionalProperties: false/)})
