export const mobileRoutes = {
  home: '/m',
  converter: '/m/op/converter',
  offer: '/m/op/offer',
  logs: '/m/op/logs',
  espelhar: '/m/op/espelhar',
  configWhatsApp: '/m/config/whatsapp',
  configGroups: '/m/config/groups',
  configCredentials: '/m/config/credentials',
  configPreferences: '/m/config/preferences',
  helpTutorial: '/m/help/tutorial',
  tutorial: '/m/tutorial',
  account: '/m/account',
  accountSubscription: '/m/account/subscription',
  accountTemplates: '/m/account/templates',
  checklistEspelhamento: '/m/checklistespelhamento',
  preservacao: '/m/config/preservacao',
  scheduled: '/m/op/scheduled',
}
