import axios from 'axios'
import crypto from 'crypto'
import { shouldConvertCouponLinks } from './couponPolicy.js'

const ENDPOINT = 'https://open-api.affiliate.shopee.com.br/graphql'

// Códigos com que a Shopee recusa a CHAVE INTEIRA. Só estes viram
// `alive:false` na sondagem — que dispara o e-mail `chave_shopee_recusada`
// ("as ofertas da Shopee pararam de sair"). Qualquer outro código fica
// INDETERMINADO: avisar que a cliente parou de vender quando não parou é pior
// do que não avisar (mesma regra de `alive === null` em
// credentialExpiry/policy.js). Código só entra aqui com MEDIÇÃO.
//
// 10020 = "Invalid Signature" (RCA 2026-08).
// 10035 = "You currently do not have access to the Shopee Affiliate Open API
//   Platform" (RCA 2026-09-23, conta nandavieiraf@gmail.com). Medido com a
//   chave real, operação por operação: `productOfferV2` por palavra-chave,
//   `productOfferV2` por produto e `generateShortLink` (a conversão do
//   espelhamento) — as TRÊS devolvem 10035, enquanto a chave de outra conta,
//   no mesmo instante, responde OK. Um App ID inventado também recebe 10035
//   nas duas operações: é a resposta da Shopee para App ID que ela não
//   reconhece. Nos envios da conta: 933 falhas de conversão + 923
//   `skip:no_valid_conversions` contra 136 sucessos em 72h.
//   ⚠️ Uma versão intermediária tirou 10035 daqui supondo que só o catálogo
//   estava bloqueado ("o espelhamento continua funcionando"). A medição
//   derrubou isso — não repetir sem medir `generateShortLink` com a chave.
export const SHOPEE_AUTH_REJECTED_CODES = Object.freeze([10020, 10035])

// Estágio de diagnóstico para um erro no corpo da resposta: separa chave
// recusada (ação: recadastrar o App ID/chave) do erro genérico.
function stageForShopeeApiError(apiError) {
  const code = Number(apiError?.extensions?.code ?? apiError?.code)
  return SHOPEE_AUTH_REJECTED_CODES.includes(code) ? 'shopee_chave_recusada' : 'shopee_api_erro'
}

// SubID fixo enviado em TODO link de afiliado que geramos. Não é configuração
// de ambiente nem campo por cliente de propósito: é requisito de produto (todo
// clique tem que cair no relatório da Shopee sob esta origem), e uma env
// criaria o risco de staging/prod divergirem ou de o tracking sumir por
// configuração ausente. Vale para cliente existente e futura sem migration.
export const SHOPEE_SUB_ID = 'espelhagrupos'

function buildAuth(appId, secretKey, payload) {
  const timestamp = Math.floor(Date.now() / 1000)
  const sig = crypto
    .createHash('sha256')
    .update(`${appId}${timestamp}${payload}${secretKey}`)
    .digest('hex')
  return {
    header: `SHA256 Credential=${appId}, Timestamp=${timestamp}, Signature=${sig}`,
    timestamp,
  }
}

// Strips noise from a resolved Shopee affiliate URL, keeping only the params
// that matter for commission attribution. This is kept as a diagnostic/fallback
// helper for scrapers/tests, but convert() must return the official shortLink
// generated by Shopee's affiliate API (s.shopee.com.br/shope.ee). Returning the
// resolved product URL caused mirrored messages to expose long non-short links
// and made it hard to visually verify affiliate attribution. Essential affiliate
// params are:
//   utm_medium  — identifies the channel as "affiliates"
//   utm_source  — identifies the affiliate (an_{appId})
//   mmp_pid     — MMP click-level attribution
//   uls_trackid — Shopee's unique link tracking ID for this conversion
// Everything else is stripped. If no product IDs can be extracted (edge case),
// the resolved URL is returned as-is rather than silently losing the link.
export function cleanAffiliateUrl(resolvedUrl) {
  const ids = extractShopeeIds(resolvedUrl)
  if (!ids) return resolvedUrl
  let params
  try { params = new URL(resolvedUrl).searchParams } catch { params = new URLSearchParams() }
  const kept = new URLSearchParams()
  for (const key of ['utm_medium', 'utm_source', 'mmp_pid', 'uls_trackid']) {
    const val = params.get(key)
    if (val) kept.set(key, val)
  }
  const base = `https://shopee.com.br/product/${ids.shopId}/${ids.itemId}`
  const qs = kept.toString()
  return qs ? `${base}?${qs}` : base
}

// Parâmetros de tracking/afiliado de TERCEIROS. A mutation generateShortLink
// recusa com "Invalid origin URL" quando a origin chega carimbada com o
// afiliado de ORIGEM (utm_source=an_<id>, utm_medium=affiliates, AppsFlyer
// af_*/deep_and_*, gads_t_sig, etc.) — o programa não reetiqueta link de outro
// afiliado. Esse era o ponto que fazia a conversão de cupom falhar.
const AFFILIATE_TRACKING_PARAMS = new Set([
  'utm_source', 'utm_medium', 'utm_campaign', 'utm_content', 'utm_term',
  'gads_t_sig', '__mobile__', 'smtt', 'exlid', 'xptdk',
  'mmp_pid', 'uls_trackid', 'pid', 'c', 'is_retargeting',
])

// Remove o tracking de terceiros de uma URL Shopee preservando a IDENTIDADE do
// recurso (path + promotionId/voucherCode/signature). Assim a API gera NOSSO
// shortLink apontando para o mesmo cupom, com a comissão creditada a nós. Pura
// e idempotente: sem params de tracking, devolve a URL intacta.
export function stripAffiliateTracking(rawUrl) {
  let u
  try { u = new URL(String(rawUrl)) } catch { return rawUrl }
  let changed = false
  for (const key of [...u.searchParams.keys()]) {
    const lower = key.toLowerCase()
    if (AFFILIATE_TRACKING_PARAMS.has(lower) || lower.startsWith('af_') || lower.startsWith('deep_and_')) {
      u.searchParams.delete(key)
      changed = true
    }
  }
  return changed ? u.toString() : String(rawUrl)
}

// Chama a mutation generateShortLink da API de afiliado para `originUrl` e
// devolve o shortLink oficial (ex.: https://s.shopee.com.br/2g92F2xepl). NÃO
// resolvemos para /product?... aqui: isso deixaria a mensagem com URL longa e
// poderia mascarar regressões em que a API deixa de devolver link curto.
//
// Resiliência: re-tenta APENAS falha de transporte (timeout/rede, sem resposta
// HTTP). Rejeição determinística da API (Invalid origin URL, sem shortLink, 4xx)
// não melhora com retry — aborta na primeira.
async function generateAffiliateShortLink(originUrl, { appId, secretKey }, { attempts = 2 } = {}) {
  const safeUrl = String(originUrl).replace(/\\/g, '\\\\').replace(/"/g, '\\"')
  const body = {
    query: `mutation {
      generateShortLink(input: { originUrl: "${safeUrl}", subIds: ["${SHOPEE_SUB_ID}"] }) {
        shortLink
      }
    }`,
  }
  const payload = JSON.stringify(body)
  const { header } = buildAuth(appId, secretKey, payload)

  let lastErr
  for (let attempt = 0; attempt < attempts; attempt++) {
    try {
      const { data } = await axios.post(ENDPOINT, body, {
        headers: { Authorization: header, 'Content-Type': 'application/json' },
        timeout: 8000,
      })
      const link = data?.data?.generateShortLink?.shortLink
      if (!link) throw new Error(data?.errors?.[0]?.message || 'Resposta inesperada')
      return assertShopeeAffiliateShortLink(link)
    } catch (err) {
      lastErr = err
      if (err.response) break // resposta HTTP de erro = determinístico
    }
  }
  throw new Error(`Shopee converter: ${lastErr.message}`)
}

export async function convert(url, creds) {
  const canonical = await resolveCanonical(url)

  // Se a resolução server-side do short link cair em /unsupported.html, NÃO
  // use essa URL como originUrl da generateShortLink. Esse foi o caso observado
  // em staging: o servidor resolve o short do concorrente para a parede web da
  // Shopee; encurtar essa parede gera um shortLink nosso que nasce quebrado.
  // Para não sumir com o cupom, tentamos reetiquetar o próprio short link
  // original (s.shopee.com.br/...) — a API da Shopee é quem decide se aceita.
  // Se recusar, caímos no strip seguro abaixo, sem vazar afiliado de terceiro.
  const originCandidate = isShopeeUnsupportedUrl(canonical) && isShopeeShortLink(url)
    ? String(url)
    : canonical

  // Produto: a URL canônica já vem como /product/{shopId}/{itemId}
  // (normalizeShopeeUrl), limpa e aceita pela API. Caminho inalterado.
  if (extractShopeeIds(originCandidate)) {
    const shortLink = await generateAffiliateShortLink(originCandidate, creds)
    return { url: shortLink, linkKind: 'product' }
  }

  // Cupom/voucher/campanha (sem shopId+itemId). Com COUPON_LINK_CONVERT
  // ligado, converte pela API de afiliado PRESERVANDO o caminho original do
  // cupom — só removendo o tracking do afiliado de ORIGEM (que a API recusaria
  // com "Invalid origin URL"). O short link gerado abre direto o app da Shopee,
  // igual aos links de produto.
  //
  // NÃO reescrevemos o caminho para uma landing web (ex.: `/m/cupom-de-desconto`).
  // Um probe contra a API real em staging provou que a `generateShortLink` gera
  // um short link `s.shopee.com.br/XXX` que ABRE O APP para a origem natural do
  // cupom (qualquer caminho `/m/...`, `/buyer/voucher`, etc.). Reescrever para a
  // landing web era JUSTAMENTE o que transformava um link app-deeplink numa
  // página web bloqueada pelo WebView do WhatsApp ("Oops! Seu navegador não é
  // mais aceito!"). Devolvemos o short link como-está, como no caminho de produto.
  if (shouldConvertCouponLinks()) {
    const origin = stripAffiliateTracking(originCandidate)
    try {
      const shortLink = await generateAffiliateShortLink(origin, creds)
      return { url: shortLink, linkKind: 'coupon' }
    } catch {
      // Fallback seguro: se a Shopee recusar a origin, removemos o link para
      // nunca vazar afiliado de terceiro.
    }
  }

  const err = new Error('link não é de produto — removido para evitar atribuição incorreta de comissão')
  err.stripFromMessage = true
  throw err
}

// Resolve short links (shope.ee, s.shopee.com.br) para a URL canônica
// e normaliza para o formato que a API de afiliado aceita como origem.
//
// Shopee BR ressuscitou em 2026 um shortlink no formato `/opaanlp/{shopId}/{itemId}`
// (campanha "Open Anuncio Link de Produto") já carimbado como afiliado de
// terceiros (`utm_medium=affiliates&utm_source=an_<id>` + assinatura
// `gads_t_sig`). A `generateShortLink` recusa URLs assim com "Invalid origin URL"
// porque o programa não reetiqueta link de outro afiliado. Solução: extrair
// (shopId, itemId) do path e reescrever para `/product/{shopId}/{itemId}` sem
// query string — formato canônico aceito.
const SHOPEE_PRODUCT_PATH_RE = /\/(?:opaanlp|product|universal-link\/product)\/(\d+)\/(\d+)(?=[/?#&%]|$)/
const SHOPEE_DASH_I_RE = /-i\.(\d+)\.(\d+)(?=[/?#&%]|$)/
const SHOPEE_SHORT_HOST_RE = /^(shope\.ee|s\.shopee\.com\.br)$/
const SHOPEE_BROWSER_UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'
const SHORT_LINK_MAX_HOPS = 6
const SHORT_LINK_BODY_MAX_BYTES = 512 * 1024

function isShopeeUnsupportedUrl(rawUrl) {
  try {
    const u = new URL(String(rawUrl || ''))
    return /(^|\.)shopee\.com\.br$/.test(u.hostname) && u.pathname === '/unsupported.html'
  } catch {
    return false
  }
}

export function isShopeeShortLink(url) {
  try {
    return SHOPEE_SHORT_HOST_RE.test(new URL(String(url || '')).hostname)
  } catch {
    return false
  }
}

function assertShopeeAffiliateShortLink(link) {
  if (!link || !isShopeeShortLink(link)) {
    throw new Error('API da Shopee não retornou shortLink afiliado válido')
  }
  return link
}

// Extrai (shopId, itemId) de qualquer string que contenha uma URL de produto
// Shopee — inclusive quando a URL do produto está URL-encoded dentro de um
// query param (ex.: página anti-bot `verify/traffic?next=https%3A%2F%2F...`).
// É a ÚNICA fonte de verdade de parsing de IDs; productInfoScraper e
// imageScrapers delegam para cá.
export function extractShopeeIds(value) {
  let text = String(value || '')
  for (let round = 0; round < 3; round++) {
    const m = text.match(SHOPEE_DASH_I_RE) || text.match(SHOPEE_PRODUCT_PATH_RE)
    if (m) return { shopId: m[1], itemId: m[2] }
    let decoded
    try { decoded = decodeURIComponent(text) } catch { break }
    if (decoded === text) break
    text = decoded
  }
  return null
}

export function normalizeShopeeUrl(rawUrl) {
  try {
    const u = new URL(rawUrl)
    if (!/(^|\.)shopee\.com\.br$/.test(u.hostname)) return rawUrl
    const ids = extractShopeeIds(rawUrl)
    if (ids) return `https://shopee.com.br/product/${ids.shopId}/${ids.itemId}`
    return rawUrl
  } catch { return rawUrl }
}

function collectSetCookies(res, jar) {
  const headers = res?.headers
  let lines = []
  if (typeof headers?.getSetCookie === 'function') {
    lines = headers.getSetCookie() || []
  } else {
    const single = headers?.get?.('set-cookie')
    if (single) lines = [single]
  }
  for (const line of lines) {
    const pair = String(line).split(';')[0]
    const eq = pair.indexOf('=')
    if (eq > 0) jar.set(pair.slice(0, eq).trim(), pair.slice(eq + 1).trim())
  }
}

function decodeHtmlUrl(raw) {
  return String(raw || '').replace(/\\\//g, '/').replace(/&amp;/g, '&').trim()
}

// Quando o short link responde 200 (interstitial de tracking) em vez de
// redirect HTTP, o destino real fica no corpo: meta refresh, redirect JS
// (`location.replace(...)`), og:url/canonical ou uma URL de produto embutida.
function extractRedirectTargetFromHtml(html, baseUrl) {
  if (!html) return null
  const candidates = []
  const metaRefresh = html.match(/http-equiv=["']?refresh["']?[^>]*content=["'][^"']*url\s*=\s*([^"'>\s]+)/i)
  if (metaRefresh?.[1]) candidates.push(metaRefresh[1])
  const jsRedirect = html.match(/location\.(?:replace|assign)\(\s*["']([^"']+)["']/i)
    || html.match(/location(?:\.href)?\s*=\s*["']([^"']+)["']/i)
  if (jsRedirect?.[1]) candidates.push(jsRedirect[1])
  for (const re of [
    /<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']+)["']/i,
    /<meta[^>]+property=["']og:url["'][^>]+content=["']([^"']+)["']/i,
    /<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:url["']/i,
  ]) {
    const m = html.match(re)
    if (m?.[1]) candidates.push(m[1])
  }
  const embedded = html.match(/https?:(?:\\\/\\\/|\/\/)[^"'<>\s]*?(?:-i\.\d+\.\d+|(?:\\\/|\/)(?:product|opaanlp)(?:\\\/|\/)\d+(?:\\\/|\/)\d+)[^"'<>\s]*/i)
  if (embedded?.[0]) candidates.push(embedded[0])

  let fallback = null
  for (const raw of candidates) {
    let abs
    try { abs = new URL(decodeHtmlUrl(raw), baseUrl).href } catch { continue }
    if (extractShopeeIds(abs)) return abs
    if (!fallback) fallback = abs
  }
  return fallback
}

async function readBodyLimited(res) {
  try {
    if (!res?.body?.getReader) {
      const text = await res?.text?.()
      return typeof text === 'string' ? text.slice(0, SHORT_LINK_BODY_MAX_BYTES) : null
    }
    const reader = res.body.getReader()
    const chunks = []
    let received = 0
    while (received < SHORT_LINK_BODY_MAX_BYTES) {
      const { done, value } = await reader.read()
      if (done) break
      chunks.push(value)
      received += value.byteLength
    }
    await reader.cancel().catch(() => {})
    const body = new Uint8Array(received)
    let offset = 0
    for (const chunk of chunks) {
      body.set(chunk, offset)
      offset += chunk.byteLength
    }
    return new TextDecoder().decode(body)
  } catch {
    return null
  }
}

// Resolvedor canônico de short link da Shopee. NÃO usar fetch(redirect:'follow')
// direto: a Shopee intercala hops de anti-bot (verify/traffic) no FIM da cadeia
// e serve interstitials 200 com redirect via JS — nos dois casos o `res.url`
// final perde a URL do produto e TODAS as fontes de título/preço/imagem morrem
// juntas (afiliado GraphQL, API v4 e título via slug dependem dos IDs).
// Estratégia: seguir os redirects manualmente carregando cookies da cadeia e
// parar no PRIMEIRO hop cuja URL já contenha (shopId, itemId) — inclusive
// URL-encoded em query param. Sem redirect HTTP, extrai o alvo do corpo.
// Cache da resolução (RCA 2026-08-26). Motivo medido em produção: a MESMA URL
// curta é resolvida três vezes por mensagem — na conversão, na busca de
// título/preço e na busca da foto —, e cada resolução é uma cadeia de vários
// redirects, cada hop com seu próprio timeout. Quando um hop estoura, a função
// devolve a URL curta como veio (sem ids) e QUEM CHAMOU não tem como saber:
// para a foto isso vira `null` silencioso, e a oferta sai com a miniatura de
// 500 bytes da mensagem de origem em vez da foto da loja.
//
// Medição: 780 de 2000 buscas de foto de Shopee no log voltaram sem URL, e os
// nulos estavam concentrados no worker mais movimentado — o mesmo link que
// resolve de primeira num teste isolado falha sob carga. Short link da Shopee é
// imutável, então cachear a resolução BEM-SUCEDIDA é seguro e elimina duas das
// três idas à rede.
const SHORT_LINK_CACHE_TTL_MS = Math.max(0, Number(process.env.SHOPEE_SHORTLINK_CACHE_TTL_MS || 6 * 60 * 60 * 1000))
const SHORT_LINK_CACHE_MAX = 2_000
const shortLinkCache = new Map()

function getCachedShortLink(url) {
  if (!SHORT_LINK_CACHE_TTL_MS) return null
  const hit = shortLinkCache.get(url)
  if (!hit) return null
  if (hit.expiresAt < Date.now()) {
    shortLinkCache.delete(url)
    return null
  }
  return hit.value
}

function setCachedShortLink(url, value) {
  if (!url || !SHORT_LINK_CACHE_TTL_MS) return
  // Só cacheia resolução ÚTIL: guardar um fracasso transformaria uma falha
  // pontual de rede em "esse link não tem produto" pelas próximas horas.
  if (!extractShopeeIds(value)) return
  if (shortLinkCache.size >= SHORT_LINK_CACHE_MAX) {
    const primeira = shortLinkCache.keys().next().value
    if (primeira !== undefined) shortLinkCache.delete(primeira)
  }
  shortLinkCache.set(url, { value, expiresAt: Date.now() + SHORT_LINK_CACHE_TTL_MS })
}

export function _resetShopeeShortLinkCache() {
  shortLinkCache.clear()
}

export async function resolveShopeeShortLink(url, { timeoutMs = 8000, fetchImpl = globalThis.fetch } = {}) {
  let current = String(url || '')
  if (!isShopeeShortLink(current)) return current

  // `fetchImpl` injetado = cenário controlado (teste/stub): o cache guardaria o
  // resultado de um stub e vazaria para a chamada seguinte. Só cacheia o
  // caminho real.
  const podeCachear = fetchImpl === globalThis.fetch
  const cached = podeCachear ? getCachedShortLink(current) : null
  if (cached) return cached
  const original = podeCachear ? current : null

  const jar = new Map()
  for (let hop = 0; hop < SHORT_LINK_MAX_HOPS; hop++) {
    if (extractShopeeIds(current)) {
      setCachedShortLink(original, current)
      return current
    }

    let res
    try {
      const cookieHeader = [...jar.entries()].map(([name, value]) => `${name}=${value}`).join('; ')
      res = await fetchImpl(current, {
        headers: {
          'User-Agent': SHOPEE_BROWSER_UA,
          Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
          'Accept-Language': 'pt-BR,pt;q=0.9,en;q=0.8',
          ...(cookieHeader ? { Cookie: cookieHeader } : {}),
        },
        redirect: 'manual',
        signal: AbortSignal.timeout(timeoutMs),
      })
    } catch {
      return current
    }

    collectSetCookies(res, jar)

    const location = res?.headers?.get?.('location')
    if (location) {
      try { current = new URL(location, current).href } catch { return current }
      continue
    }

    // Implementações de fetch que seguem redirects sozinhas reportam a URL
    // final em res.url mesmo com redirect:'manual' (e.g. proxies/stubs).
    if (res?.url && res.url !== current) {
      current = res.url
      continue
    }

    const html = await readBodyLimited(res)
    const target = extractRedirectTargetFromHtml(html, current)
    if (target && target !== current) {
      current = target
      continue
    }
    setCachedShortLink(original, current)
    return current
  }
  setCachedShortLink(original, current)
  return current
}

async function resolveCanonical(url) {
  try {
    const resolved = await resolveShopeeShortLink(url, { timeoutMs: 5000 })
    return normalizeShopeeUrl(resolved)
  } catch { return url }
}

function parseIds(url) {
  return extractShopeeIds(url)
}

// Consulta a API de afiliado (GraphQL) para obter a imagem oficial do produto.
// Mais confiável que scraping HTML, que a Shopee bloqueia para UAs comuns.
// A Shopee tem UMA fonte de foto que funciona: esta API de afiliado. O shell
// SPA da página não traz og:image e a API v4 pública responde com erro
// (documentado no AGENTS.md, seção "Image scrapers"). Ou seja: quando isto aqui
// devolve `null`, a oferta de Shopee fica sem foto de loja — e até 2026-08-26
// esse caminho era MUDO (dois `catch` vazios), então não dava para saber se foi
// chave recusada, item fora do catálogo de afiliado ou short link não resolvido.
// O Mercado Livre não sofre disso porque tem vitrine + API + página como fontes.
//
// `onDiagnostic({ stage, detail })` é opcional e best-effort: quem chama decide
// se loga/emite sinal. Nunca altera o retorno.
export async function fetchShopeeImage(url, creds, { onDiagnostic } = {}) {
  const report = (stage, detail) => {
    try { onDiagnostic?.({ stage, detail }) } catch {}
  }
  if (!creds?.appId || !creds?.secretKey) {
    report('shopee_sem_credencial')
    return null
  }
  const canonical = await resolveCanonical(url)
  const ids = parseIds(canonical)
  if (!ids) {
    report('shopee_sem_ids', canonical)
    return null
  }

  const body = {
    query: `{
      productOfferV2(itemId: ${ids.itemId}, shopId: ${ids.shopId}, listType: 0, sortType: 2, page: 1, limit: 1) {
        nodes { imageUrl productName }
      }
    }`,
  }
  const payload = JSON.stringify(body)
  const { header } = buildAuth(creds.appId, creds.secretKey, payload)

  try {
    const { data } = await axios.post(ENDPOINT, body, {
      headers: { Authorization: header, 'Content-Type': 'application/json' },
      timeout: 6000,
    })
    // A API de afiliado responde 200 MESMO EM ERRO, sinalizando via `errors`
    // (mesma armadilha da sondagem de credencial — ver checkShopeeSession).
    // Sem ler o corpo, chave recusada (10020) parecia "produto sem foto".
    const apiError = Array.isArray(data?.errors) ? data.errors[0] : null
    if (apiError) {
      report(stageForShopeeApiError(apiError), apiError?.message || apiError?.code || 'erro sem detalhe')
      return null
    }
    const node = data?.data?.productOfferV2?.nodes?.[0]
    if (!node?.imageUrl) {
      // Catálogo de afiliado não tem esse item: acontece e não é defeito nosso.
      report('shopee_item_fora_do_catalogo', `${ids.shopId}/${ids.itemId}`)
      return null
    }
    return node.imageUrl
  } catch (err) {
    report('shopee_api_falhou', err?.message)
    return null
  }
}

// A API de afiliado (productOfferV2) devolve os preços como string decimal em
// reais (ex.: "59.9"), NÃO em micro-unidades. Por isso aqui é só normalizar o
// decimal para o formato pt-BR "59,90" — diferente do payload da API v4 pública
// (item/get) que vem em centavos*100000 e é tratado em productInfoScraper.js.
export function shopeeDecimalPriceToString(value) {
  const num = Number(value)
  if (!Number.isFinite(num) || num <= 0) return ''
  return num.toFixed(2).replace('.', ',')
}

// Consulta a API de afiliado (GraphQL) para obter título e preço do produto.
// Retorna { title, newPrice, oldPrice } ou null em caso de falha/sem creds.
//
// Campos confirmados do schema productOfferV2 (2026-06): price, priceMin,
// priceMax, priceDiscountRate, productName, imageUrl. NÃO existe `originPrice`
// (pedir esse campo derruba a query inteira com erro 10010). O preço "de" é
// derivado do preço atual + a taxa de desconto inteira (`priceDiscountRate`).
//
// `onDiagnostic({ stage, detail })` é opcional e best-effort — mesmo contrato
// de `fetchShopeeImage`. Até 2026-09-23 este caminho era tão MUDO quanto o da
// foto era antes do RCA 2026-09-16: qualquer erro (chave recusada, item fora
// do catálogo, API fora do ar) virava o MESMO `null`, e "Criar oferta" saía
// sem nome nem preço sem uma linha de log sequer explicando por quê.
export async function fetchShopeeProductInfo(url, creds, { onDiagnostic } = {}) {
  const report = (stage, detail) => {
    try { onDiagnostic?.({ stage, detail }) } catch {}
  }
  if (!creds?.appId || !creds?.secretKey) {
    report('shopee_sem_credencial')
    return null
  }
  try {
    const canonical = await resolveCanonical(url)
    const ids = parseIds(canonical)
    if (!ids) {
      report('shopee_sem_ids', canonical)
      return null
    }

    const body = {
      query: `{
        productOfferV2(itemId: ${ids.itemId}, shopId: ${ids.shopId}, listType: 0, sortType: 2, page: 1, limit: 1) {
          nodes { imageUrl productName price priceMin priceMax priceDiscountRate }
        }
      }`,
    }
    const payload = JSON.stringify(body)
    const { header } = buildAuth(creds.appId, creds.secretKey, payload)

    const { data } = await axios.post(ENDPOINT, body, {
      headers: { Authorization: header, 'Content-Type': 'application/json' },
      timeout: 6000,
    })
    // A API de afiliado responde 200 MESMO EM ERRO, sinalizando via `errors`
    // (mesma armadilha da sondagem de credencial e da busca de foto). Sem ler
    // o corpo, chave recusada ou sem acesso à plataforma (10020/10035) parecia
    // "produto sem título/preço".
    const apiError = Array.isArray(data?.errors) ? data.errors[0] : null
    if (apiError) {
      report(stageForShopeeApiError(apiError), apiError?.message || apiError?.code || 'erro sem detalhe')
      return null
    }
    const node = data?.data?.productOfferV2?.nodes?.[0]
    if (!node) {
      report('shopee_item_fora_do_catalogo', `${ids.shopId}/${ids.itemId}`)
      return null
    }

    const title = typeof node.productName === 'string' ? node.productName.trim() : ''
    const currentRaw = node.priceMin ?? node.price ?? null
    const newPrice = shopeeDecimalPriceToString(currentRaw)

    // Preço "de": reconstruído a partir do desconto. priceDiscountRate é a % de
    // desconto inteira (ex.: 54 = 54% off), então original = atual / (1 - rate/100).
    let oldPrice = ''
    const rate = Number(node.priceDiscountRate)
    const current = Number(currentRaw)
    if (Number.isFinite(rate) && rate > 0 && rate < 100 && Number.isFinite(current) && current > 0) {
      oldPrice = shopeeDecimalPriceToString(current / (1 - rate / 100))
    }

    if (!title && !newPrice) {
      report('shopee_catalogo_sem_titulo_ou_preco', `${ids.shopId}/${ids.itemId}`)
      return null
    }
    return { title, newPrice, oldPrice }
  } catch (err) {
    report('shopee_api_falhou', err?.message)
    return null
  }
}

// ---------------------------------------------------------------------------
// Sondagem de saúde da chave da Shopee (App ID + chave secreta).
//
// Por que existe: quando a Shopee passa a recusar a chave, TODA conversão da
// loja falha e as ofertas automáticas param — e isso acontecia em SILÊNCIO. O
// caso real (ago/2026) ficou dias assim: `Invalid Signature` no log, ofertas
// virando `skip:no_valid_conversions`, e nenhum aviso em lugar nenhum. Foi
// descoberto só porque alguém foi investigar à mão.
//
// Diferente do ML/Amazon, aqui não é "código que vence": a chave é recusada de
// uma vez. O contrato de retorno é o MESMO de checkMercadoLivreSession /
// checkAmazonSession — { configured, alive, reason } — para o aviso por e-mail
// tratar as três lojas pelo mesmo caminho.

// `SHOPEE_AUTH_REJECTED_CODES` mora no topo do arquivo (com a medição que
// decidiu cada código).

// Consulta só de leitura, sem efeito colateral: não gera link nem grava nada do
// lado da Shopee. O que importa é se a assinatura é aceita.
const SESSION_PROBE_QUERY = '{ productOfferV2(keyword: "teste", listType: 1, sortType: 2, page: 1, limit: 1) { nodes { itemId } } }'

/**
 * Decisão pura sobre a resposta da sondagem — separada do I/O para ser testável
 * sem rede.
 *
 * A API de afiliado responde **200 mesmo em erro**, sinalizando via `errors`
 * (mesma pegadinha já documentada em offerAutomation/shopeeOffers.js). Por isso
 * a classificação olha o corpo, não só o status.
 *
 * @param {{ status?: number, errors?: Array<{extensions?:{code?:number}, code?:number, message?:string}>, hasNodes?: boolean }} response
 * @returns {{ configured: boolean, alive: boolean|null, reason: string }}
 */
export function classifyShopeeProbeResponse({ status, errors, hasNodes } = {}) {
  if (Number.isFinite(status) && status !== 200) {
    return { configured: true, alive: null, reason: 'http_error' }
  }

  const list = Array.isArray(errors) ? errors : []
  if (list.length) {
    const codes = list.map((e) => Number(e?.extensions?.code ?? e?.code)).filter(Number.isFinite)
    if (codes.some((code) => SHOPEE_AUTH_REJECTED_CODES.includes(code))) {
      return { configured: true, alive: false, reason: 'rejected' }
    }
    // Rate limit, indisponibilidade, consulta sem permissão: não prova que a
    // chave morreu.
    return { configured: true, alive: null, reason: 'api_error' }
  }

  if (hasNodes) return { configured: true, alive: true, reason: 'ok' }

  // 200, sem erro e sem o campo esperado: contrato mudou ou resposta truncada.
  return { configured: true, alive: null, reason: 'unexpected_response' }
}

/**
 * @param {{ appId?: string, secretKey?: string }} creds
 * @param {{ axiosImpl?: object, timeoutMs?: number }} [deps]
 * @returns {Promise<{ configured: boolean, alive: boolean|null, reason: string }>}
 */
export async function checkShopeeSession(creds = {}, { axiosImpl = axios, timeoutMs = 8000 } = {}) {
  const appId = String(creds?.appId ?? '').trim()
  const secretKey = String(creds?.secretKey ?? '').trim()
  // Falta de campo é outro problema (o painel já diz "falta preencher").
  if (!appId || !secretKey) return { configured: false, alive: null, reason: 'no_credentials' }

  const body = { query: SESSION_PROBE_QUERY }
  const payload = JSON.stringify(body)
  const { header } = buildAuth(appId, secretKey, payload)

  try {
    const { status, data } = await axiosImpl.post(ENDPOINT, body, {
      headers: { Authorization: header, 'Content-Type': 'application/json' },
      timeout: timeoutMs,
    })
    return classifyShopeeProbeResponse({
      status,
      errors: data?.errors,
      hasNodes: Array.isArray(data?.data?.productOfferV2?.nodes),
    })
  } catch (err) {
    // Rede/timeout/5xx nunca viram "sua chave morreu".
    const status = Number(err?.response?.status)
    if (Number.isFinite(status)) {
      return classifyShopeeProbeResponse({ status, errors: err?.response?.data?.errors })
    }
    return { configured: true, alive: null, reason: 'network_error' }
  }
}
