'use client'
import { useState } from 'react'
import { api } from '@/lib/api'
const mb = (value) => value == null ? '—' : `${Math.round(value)} MB`
const percent = (value) => value == null ? '—' : `${Number(value).toFixed(1)}%`
const duration = (seconds) => seconds == null ? '—' : seconds >= 86400 ? `${Math.floor(seconds / 86400)}d ${Math.floor(seconds % 86400 / 3600)}h` : seconds >= 3600 ? `${Math.floor(seconds / 3600)}h ${Math.floor(seconds % 3600 / 60)}min` : `${Math.floor(seconds / 60)}min`
const statusLabel = { offline: 'Desligado', online: 'Ligado', partial: 'Parcial', unknown: 'Desconhecido' }
export default function CapacityEnvironments({ environments = [], suggestion, divergences = [], canManage = false, onChanged }) {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState('')
  async function stopStaging() { if (!window.confirm('Desligar API e dashboard de staging? Faça isso somente se não houver validação em curso.')) return; setBusy(true); setMessage(''); try { await api.adminStagingPower('off'); setMessage('Comando enviado com sucesso.'); onChanged?.() } catch (error) { setMessage(error?.message || 'Não foi possível desligar staging.') } finally { setBusy(false) } }
  return <section className="rounded-2xl border border-slate-200 bg-white p-5" aria-labelledby="capacity-env-title"><h2 id="capacity-env-title" className="text-lg font-black text-slate-950">Ambientes</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{environments.map((env) => <article key={env.environment} className="rounded-xl bg-slate-50 p-4"><div className="flex items-center justify-between"><h3 className="font-black capitalize">{env.environment === 'production' ? 'Produção' : 'Staging'}</h3><span className="text-xs font-bold uppercase">{statusLabel[env.status] || 'Desconhecido'}</span></div><p className="mt-2 text-sm tabular-nums">{env.workers ?? '—'} workers · {mb(env.rssMb)}</p><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[540px] text-left text-xs text-slate-700"><caption className="sr-only">Estado e consumo dos aplicativos de {env.environment === 'production' ? 'produção' : 'staging'}</caption><thead><tr><th className="pb-1">App</th><th>Estado</th><th>CPU</th><th>Memória</th><th>Reinícios</th><th>Tempo ativo</th></tr></thead><tbody>{env.apps.map((app, i) => <tr key={`${app.key}-${i}`} className="border-t border-slate-200"><td className="py-1 font-semibold">{app.key}</td><td>{app.status || 'unknown'}</td><td className="tabular-nums">{percent(app.cpuPercent)}</td><td className="tabular-nums">{mb(app.rssMb)}</td><td className="tabular-nums">{app.restartCount ?? '—'}</td><td className="tabular-nums">{duration(app.uptimeSeconds)}</td></tr>)}</tbody></table></div>{env.controlScope && <p className="mt-3 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs font-semibold text-amber-950">{env.controlScope.message} Controlados: {env.controlScope.managedApps.join(', ')}. Independente: {env.controlScope.unmanagedApps.join(', ')}.</p>}</article>)}</div>{divergences.map((item) => <p role="status" className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-950" key={item.code}>{item.message}</p>)}{suggestion && <div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl bg-cyan-50 p-4"><p className="text-sm text-cyan-950">{suggestion.message}</p>{canManage && <button type="button" disabled={busy} onClick={stopStaging} className="min-h-11 rounded-xl bg-slate-950 px-4 py-2 font-bold text-white disabled:opacity-50">{busy ? 'Desligando…' : 'Desligar API e dashboard de staging'}</button>}</div>}<p aria-live="polite" className="mt-2 text-sm text-slate-700">{message}</p></section>
}
