'use client'
import { useState } from 'react'
import { api } from '@/lib/api'
export default function CapacityScenarioSimulator() {
  const [form, setForm] = useState({ newCustomers: 10, horizonMonths: 3, activationPercent: 90, stagingExpectedOn: false }); const [result, setResult] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value })); const numberInput = (key) => (event) => update(key, event.target.value === '' ? '' : Number(event.target.value))
  async function submit(event) { event.preventDefault(); setLoading(true); setError(''); try { setResult(await api.adminCapacityScenario(form)) } catch (err) { setError(err?.message || 'Não foi possível calcular este cenário.') } finally { setLoading(false) } }
  return <section aria-labelledby="capacity-scenario-title" className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[.16em] text-cyan-700">Planejamento</p><h2 id="capacity-scenario-title" className="mt-1 text-xl font-black">Simular crescimento</h2><p className="mt-2 text-sm text-slate-600">Esta é uma simulação consultiva. Ela não salva o cenário nem altera a infraestrutura.</p><form onSubmit={submit} className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-bold">Novos clientes<input required type="number" min="0" max="10000" step="1" value={form.newCustomers} onChange={numberInput('newCustomers')} className="mt-1 min-h-11 w-full rounded-xl border px-3" /></label><label className="text-sm font-bold">Prazo em meses<input required type="number" min="1" max="36" step="1" value={form.horizonMonths} onChange={numberInput('horizonMonths')} className="mt-1 min-h-11 w-full rounded-xl border px-3" /></label><label className="text-sm font-bold">Ativação de sessões (%)<input required type="number" min="0" max="100" step="0.1" value={form.activationPercent} onChange={numberInput('activationPercent')} className="mt-1 min-h-11 w-full rounded-xl border px-3" /></label><label className="flex min-h-11 items-center gap-3 self-end rounded-xl border px-3 text-sm font-bold"><input type="checkbox" checked={form.stagingExpectedOn} onChange={(event) => update('stagingExpectedOn', event.target.checked)} /> Staging ligado</label><button disabled={loading} type="submit" className="min-h-11 rounded-xl bg-cyan-800 px-5 font-black text-white disabled:opacity-60">{loading ? 'Calculando…' : 'Calcular cenário'}</button></form><div aria-live="polite" className="mt-5">{error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-800">{error}</p>}{result && <div className="rounded-xl bg-slate-50 p-4"><h3 className="font-black">Resultado consultivo</h3><dl className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Sessões projetadas', result.projectedSessions], ['Margem', result.headroomSessions], ['Déficit', result.deficitSessions], ['Memória incremental', `${result.incrementalMemoryMb} MB`]].map(([label, value]) => <div key={label}><dt className="text-xs font-bold uppercase text-slate-500">{label}</dt><dd className="text-2xl font-black tabular-nums">{value}</dd></div>)}</dl><p className="mt-3 text-sm font-semibold">{result.recommendation}</p></div>}</div></section>
}
